### ISSUE TITLE
Sorting vendor files with gulp-angular-filesort does not work for some libraries

### ISSUE THREAD

**Issue by JWorthe** [entelect/angular-baboon#3]
They have an open issue for the problem here, but it doesn't look like they're planning on fixing it in any way. It seems the intended use for gulp-angular-filesort is for your code, not for the vendor code https://github.com/klei/gulp-angular-filesort/issues/8

My proposed fix would rather be to use gulp-order, with the order in the environment.config.js file.

**Comment by liquidcowgithub** [comment]
Thanks for the pull requests for this issue JWorthe.
I will close this only once I've had a chance to test it properly on a new project we're about to kick off in the next week or so.

**Comment by JWorthe** [comment]
Thanks. Let me know if you run into any issues.

**Comment by liquidcowgithub** [comment]
Yeah I'm happy with how this is working now. Had a similar production problem with moment.js that gulp-order fixed right up.
